### ISSUE TITLE
Convert from XML to EDI

### ISSUE THREAD

**Issue by abcdefgabcefg** [davidpeng/editools#10]
Hello, does package expose any API to convert XML to EDI?
Any help will be appreciated)))

**Comment by davidpeng** [comment]
It does, but it depends on whether the XML is in the expected layout. If the XML is in the layout that this library outputs (you can see an example at https://github.com/davidpeng/editools#converting-edi-to-xml), it can read those back in.

If you have XML with a different structure, you'd need to use an XML library to read it, extract the values, and then you can give those to EdiTools to write out into EDI (https://github.com/davidpeng/editools#writing-out-edi).

**Comment by abcdefgabcefg** [comment]
@davidpeng Got it. Thanks a lot!
