### ISSUE TITLE
EdiDocument.Save(Stream) closes the stream

### ISSUE THREAD

**Issue by ChananPublic** [davidpeng/editools#7]
Hi

I've been trying to use EdiDocument.Save(Stream) by sending in a MemoryStream. But I can't use my MemoryStream after saving, because of line 454 in EdiDocument:

using (var writer = new StreamWriter(stream))

The using-statement is closing my underlying stream. I supplied the stream so it should be my responsibility to dispose/close it.

**Comment by davidpeng** [comment]
Thanks for reporting! Fixed.
