### ISSUE TITLE
EditDocumentTest - LoadingAnXml test fails

### ISSUE THREAD

**Issue by JosephDesmet** [davidpeng/editools#9]
Hi all,

Just trying out this repo, but I'm getting a failing unit test:

Assert.Equal() Failure
                ↓ (pos 6)
Expected: ST*997^850>810*1234>>5678**123~
Actual:   ST*9970^850>810*1234000>>5678**123~
                ↑ (pos 6)
   at EdiTools.Tests.EdiDocumentTest.LoadingAnXml() in E:\Sources\editools\EdiTools.Tests\EdiDocumentTest.cs:line 296

This seems to have something to do with the Formatting of a decimal in

```
        public static string Numeric(int decimals, decimal value)
        {
            string formatted = Math.Abs(value).ToString("f" + decimals, CultureInfo.InvariantCulture).Replace(".", string.Empty).TrimStart('0');
            if (formatted == string.Empty)
                return "0";
            if (value < 0)
                return "-" + formatted;
            return formatted;
        }
```

99.7 gets formatted as 9970
1.234 gets formatted as 1234000

Not sure what the issue is here, can you guys elaborate?

**Comment by davidpeng** [comment]
Hi Joseph,

I think this is a locale-specific issue. On EdiDocumentTest.cs lines 273 and 279, the numbers are written assuming that "." is the decimal separator. When we parse the XML, we parse numbers in a locale-sensitive way, so I think in your case, "99,7" would be the text needed to represent the same numeric value.

I'll put in a fix for the test in a bit.
